namespace PCH.Core.Models;

/// <summary>
/// A unit of work shown on the dashboard. Tasks may be created manually or
/// auto-generated by a connector (e.g. from an email or booking confirmation).
/// Persisted to the <c>tasks</c> table.
/// </summary>
public class TaskItem
{
    /// <summary>Primary key.</summary>
    public int Id { get; set; }

    /// <summary>Short title shown in the task list.</summary>
    public string Title { get; set; } = string.Empty;

    /// <summary>Optional longer description or body preview.</summary>
    public string? Description { get; set; }

    /// <summary>Dashboard grouping.</summary>
    public TaskCategory Category { get; set; } = TaskCategory.General;

    /// <summary>Current lifecycle state.</summary>
    public TaskState Status { get; set; } = TaskState.Todo;

    /// <summary>Completion percentage, 0–100.</summary>
    public int Progress { get; set; }

    /// <summary>Optional deadline used for sorting and notifications.</summary>
    public DateTimeOffset? DueDate { get; set; }

    /// <summary>How this task was created.</summary>
    public ItemSource Source { get; set; } = ItemSource.Manual;

    /// <summary>
    /// Stable external identifier (e.g. email message-id) used to deduplicate
    /// auto-created tasks. Null for manually created tasks.
    /// </summary>
    public string? ExternalId { get; set; }

    /// <summary>UTC creation timestamp.</summary>
    public DateTimeOffset CreatedAt { get; set; } = DateTimeOffset.UtcNow;

    /// <summary>UTC timestamp of the last update.</summary>
    public DateTimeOffset UpdatedAt { get; set; } = DateTimeOffset.UtcNow;

    /// <summary>
    /// True once a deadline-today toast has been sent for this task.
    /// Prevents repeat notifications across the 5-minute background check cycles.
    /// </summary>
    public bool DeadlineNotified { get; set; }
}
